### ISSUE TITLE
Design changes for iOS safari

### ISSUE THREAD

**Issue by malenesoeholm** [laundree/laundree#289]
- Timeline scroll pulls down entire page in iOS Safari
- Too easy to accidentally make bookings while scrolling, would be nice with some feedback (may not just be an issue on iOS)

Based on Facebook comment by Mads Lønne Jensen:
"Det ser godt ud! Men scroll i timelinen trækker i hele siden på iOS safari. Jeg synes også det er for nemt at komme til at oprette en booking mens man scroller, så lidt feedback ville være rart"

**Comment by budde377** [comment]
We have Apps now! This is not relevant
