### ISSUE TITLE
Re-design login/sign-up

### ISSUE THREAD

**Issue by budde377** [laundree/laundree#435]
Add two "seperate" flows for sign-up. One for sign up laundry and one for sign up user. Front page should only link to "sign up your laundry". Slack login restrictions by allowing login with unverified email, but do not allow bookings and invitation of users.

**Comment by budde377** [comment]
1. Link til brugeroprettelsen under step 1 (opret) på forsiden
2. "Opret bruger"-boks ved siden af "Log ind"-boks i menuen

**Comment by malenesoeholm** [comment]
Change wording of "Forgot your password? Let us send you a new one." such that it does not give the impression that we create a new password; instead they are sent a link by e-mail to change their password.

**Comment by malenesoeholm** [comment]
Move "Login" and "Create account" buttons to the right side of the formular.

**Comment by budde377** [comment]
Redesigned
