### ISSUE TITLE
Invitation link not intuitive

### ISSUE THREAD

**Issue by malenesoeholm** [laundree/laundree#653]
Several users have not been able to use the invitation link properly. The users should follow the link when logged in, but they try doing it without being logged in, so they get confused by why they haven't been added to the laundry. Perhaps we should consider making an option to follow the link when not logged in, then being prompted to log in or create a user, and then that user will be automatically added to the laundry.

**Comment by budde377** [comment]
THIS IS NOW FIXED!!!!!!! YEEEEAHHHH!!!
